spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
    name: microconfig-test-clientxxxx

eureka:
  client:
    service-url:
      defaultZone: http://admin:enjoy@localhost:7301/eureka
info:
  app.name: microcloud-provider-product-clientvvv
  company.name: magic
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
---
server:
  port: 8102

spring:
  profiles: beta
  application:
    name: microconfig-test-client

eureka:
  client:
    service-url:
      defaultZone: http://admin:enjoy@localhost:7001/eureka
